imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, tools/php-cs-fixer/*, src/Controller/BookController.php, src/Controller/CardGameController.php]

build:
    image: default-bionic
    environment:
        node:
            version: 16
    dependencies:
        before:
            - composer install
            - npm install
            - npm run build
            - php bin/console doctrine:database:create --env=test
            - php bin/console doctrine:migrations:migrate --no-interaction --env=test

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                    # version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
                node:
                    version: 16
        analysis:
            environment:
                node:
                    version: 16
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
    tests:
        override:
            -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
